name = "BuildConstructors"
uuid = "63b9b590-f22f-4e79-810f-ea9ba6849c26"
authors = ["Robert Hentges <robert.hentges@cern.ch>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsHEP = "0d0d6f60-fb7b-48ca-90bb-e14e8b1655a7"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NumericalDistributions = "13416b18-ec19-40e4-a123-e345ab61da74"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Distributions = ">=0.25"
DistributionsHEP = "0.5.0"
JSON = ">=0.21.4"
NumericalDistributions = "0.5.3"
OrderedCollections = "1.8.1"
Parameters = "0.12.3"
Plots = ">=1"
Test = ">=1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test"]
